Skip to content
 
Search or jump to…

Pull requests
Issues
Marketplace
Explore
 
@silvershadow8 
0
0 791 silvershadow8/cicd-pipeline-train-schedule-kubernetes
forked from linuxacademy/cicd-pipeline-train-schedule-kubernetes
 Code  Pull requests 0  Projects 0  Wiki  Security  Insights  Settings
cicd-pipeline-train-schedule-kubernetes/train-schedule-kube.yml
@whboyd whboyd Update train-schedule-kube.yml
9ed7ae6 10 days ago
37 lines (34 sloc)  604 Bytes
    
kind: Service
apiVersion: v1
metadata:
  name: train-schedule-service
spec:
  type: NodePort
  selector:
    app: train-schedule
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: train-schedule-deployment
  labels:
    app: train-schedule
spec:
  replicas: 2
  selector:
    matchLabels:
      app: train-schedule
  template:
    metadata:
      labels:
        app: train-schedule
    spec:
      containers:
      - name: train-schedule
        image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
        ports:
        - containerPort: 8080
© 2019 GitHub, Inc.
Terms
Privacy
Security
Status
Help
Contact GitHub
Pricing
API
Training
Blog
About
